#!/bin/bash
set -eu
shopt -s dotglob nullglob

# Get the filenames
if [[ ${1-} = - ]]; then
	readarray -t src # stdin
	exec </dev/tty   # Reconnect terminal to stdin after reading
elif (( $# > 0 )); then
	src=("$@") # args
else
	src=(*) # current dir
fi

# Exit if no filenames found
(( ${#src[@]} )) || { echo "No files to rename."; exit 1; }

# Create temporary file for editing, clean it up on exit
tmp=$(mktemp "${TMPDIR:-/tmp}/virename.XXX")
# shellcheck disable=SC2064 # immediate $tmp expansion is intentional
trap "rm -f '$tmp'" EXIT

# Print the filenames to the temporary file
printf '%s\n' "${src[@]}" > "$tmp"

# Open an $EDITOR or vi to edit the filenames.
# Reconnect tty to the editor in case we read filenames from stdin
${EDITOR:-vi} "$tmp"

# Read the edited filenames back
readarray -t dest < "$tmp"

# Sanity check
(( ${#src[@]} == ${#dest[@]} )) || { echo "Number of lines changed, cannot proceed."; exit 1; }

# Rename the files that were edited
for ((i=0; i < ${#src[@]}; ++i)); do
	[[ ${src[i]} = "${dest[i]}" ]] || ${MV:=mv -vi} "${src[i]}" "${dest[i]}"
done

echo "Done!"
